Created html, then css of template #17 (part 1)
nikitkasss/architecture-aims pull request #1
Opened 2020-02-13 18:19 UTC by AlesiaPr

html and css код верстки первой части 17 макета (включает заголовок, architecture aims and architecture ideas)

2020-04-11 14:13 UTC, haru-ryu requested changes

2020-04-11 14:13 UTC, haru-ryu commented on source/css/header.css
> +    transition: 300ms;
Не туда повесили transition

2020-04-11 14:13 UTC, haru-ryu commented on source/css/header.css
> +    border-bottom: 6px solid #e8e8e8;
Надо будет задать начальное значение для menu__item, иначе, когда почините transition, он будет криво работать

2020-04-11 14:13 UTC, haru-ryu commented on source/index.html
> +                            <h2 class="arcitecture-aims_number">
Не уверена, что это корректно

2020-04-11 14:13 UTC, haru-ryu commented on source/index.html
> +                        <span>
Обратите внимание на валидацию

2020-04-11 14:13 UTC, haru-ryu commented on source/index.html
> +                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed lorem augue. Maecenas vehicula<br>
Фу br

2020-04-11 14:13 UTC, haru-ryu commented on source/index.html
> +                      <h1 class="create-idea_text">
h1 только один

2020-04-11 14:13 UTC, haru-ryu commented on source/css/main-section.css
> + font-style: bold;
Не font-style

2020-04-11 14:13 UTC, haru-ryu commented on source/css/main-section.css
> +    font-style: bold;
Не font-style

2020-04-11 14:13 UTC, haru-ryu commented on source/index.html
> +                        <span>
И вообще для чего использовался именно span?

2020-04-26 20:01 UTC, nikitkasss commented
@hannakrav , Добавлены новые изменения
Завершен базовый макет (html + css)

2020-04-26 20:03 UTC, closed without merging